### ISSUE TITLE
Empty actions list in a sequence of custom control topology policy definition

### ISSUE THREAD

**Issue by pehruby** [netascode/terraform-sdwan-nac-sdwan#55]
If I define custom control policy with base_action: reject (no actions specified) like this:
```yaml
          - name: CENTR-POL_1
            description: Centralized policy to Aachen
            default_action_type: accept
            sequences:
              - id: 1
                name: Route
                base_action: reject
                type: route
                ip_type: ipv4
                match_criterias:
                  omp_tag: 101334
                  vpn_list: VPN_List_EU-CLOUD1
```

during each consequent "terrafor apply" command, terraform tries to update the policy with empty action_entries list:

```
module.sdwan.sdwan_custom_control_topology_policy_definition.custom_control_topology_policy_definition["CENTR-POL_1"] will be updated in-place
  ~ resource "sdwan_custom_control_topology_policy_definition" "custom_control_topology_policy_definition" {
        id             = "5bd17043-ed54-48c3-8dec-dd56101268f2"
        name           = "CENTR-POL_1"
      ~ sequences      = [
          ~ {
              + action_entries = []
                id             = 1
                name           = "Route"
                # (4 unchanged attributes hidden)
            },
```

The state file entry  looks like:

```
sequences      = [
        {
            action_entries = []
            base_action    = "reject"
            id             = 1
            ip_type        = "ipv4"
            match_entries  = [
                {
                    omp_tag = 101334
                    type    = "ompTag"
                },
                {
                    type             = "vpnList"
                    vpn_list_id      = "c8d52c49-37a9-480b-8dc2-08762f0cb787"
                    vpn_list_version = 0
                },
            ]
            name           = "Route"
            type           = "route"
        },
```

**Comment by pehruby** [comment]
Formated output

```yaml
          - name: CENTR-POL_1
            description: xxx
            default_action_type: accept
            sequences:
              - id: 1
                #name: Drop_leaked_eu-cloud1
                name: Route
                base_action: reject
                type: route
                ip_type: ipv4
                match_criterias:
                  omp_tag: 101334
                  vpn_list: VPN_List_EU-CLOUD1
                actions:
```

```txt
terraform apply

...
#module.sdwan.sdwan_custom_control_topology_policy_definition.custom_control_topology_policy_definition["CENTR-POL_1"] will be updated in-place
  ~ resource "sdwan_custom_control_topology_policy_definition" "custom_control_topology_policy_definition" {
        id             = "500f7a16-069b-4549-953d-b4bbb8f79c26"
        name           = "CENTR-POL_1"
      ~ sequences      = [
          ~ {
              + action_entries = []
                id             = 1
                name           = "Route"
                # (4 unchanged attributes hidden)
            },
```

State file:

```txt
terraform state show 'module.sdwan.sdwan_custom_control_topology_policy_definition.custom_control_topology_policy_definition["CENTR-POL_1"]'
#module.sdwan.sdwan_custom_control_topology_policy_definition.custom_control_topology_policy_definition["CENTR-POL_1"]:
resource "sdwan_custom_control_topology_policy_definition" "custom_control_topology_policy_definition" {
    default_action = "accept"
    description    = "xxx"
    id             = "500f7a16-069b-4549-953d-b4bbb8f79c26"
    name           = "CENTR-POL_1"
    sequences      = [
        {
            action_entries = []
            base_action    = "reject"
            id             = 1
            ip_type        = "ipv4"
            match_entries  = [
                {
                    omp_tag = 101334
                    type    = "ompTag"
                },
                {
                    type             = "vpnList"
                    vpn_list_id      = "29b4d293-16ef-4d92-903e-112040b45cb6"
                    vpn_list_version = 0
                },
            ]
            name           = "Route"
            type           = "route"
        },
```
